export {
  addArticle,
  removeArticle,
  setCurrentReferenceType,
  setAdditionalInformation,
  setCurrentArticle,
  setIdentifiers,
  setPublicationDetails,
  setCurrentArticleTitle,
  setCurrentAuthors,
  resetArticle,
  setCurrentUrls,
  setCurrentNoteBooks,
  addNoteBook,
  initNewArticle,
  setNewArticleReferenceType,
  setNewArticleTitle,
  setNewArticleAuthors,
  setNewArticlePublicationDetails,
  setNewArticleAdditionalInformation,
  articleSlice
} from './articleSlice.ts'
