version: "3.4"

networks:
  pal-network:

volumes:
  node_modules:
  uploads:

services:
  frontend:
    build:
      context: frontend
      target: development
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    restart: always
    environment:
      NODE_PATH: /usr/src/app/node_modules
    networks:
      - pal-network
  backend:
    build:
      context: ./backend
      target: builder
    volumes:
      - ./backend/app:/app
      - uploads:/uploads/
    env_file:
      - .env
    restart: always
    networks:
      - pal-network
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    networks:
      - pal-network
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - .env
    networks:
      - pal-network
    depends_on:
      - mongo
  nginx:
    restart: always
    build: ./nginx/
    volumes:
      - ./nginx/ssl/key.pem:/root/ssl/key.pem
      - ./nginx/ssl/cert.pem:/root/ssl/cert.pem
      - ./logs/nginx:/var/log/nginx/
      - uploads:/www/media/
    ports:
      - "443:443"
    depends_on:
      - backend
      - frontend
      - mongo
      - mongo-express
    networks:
      - pal-network
