version: "3.4"

networks:
  pal-network:

volumes:
  uploads:
  data_es:

services:
  frontend:
    image: "node:18"
    user: "root"
    working_dir: "/usr/src/app"
    volumes:
      - ./frontend:/usr/src/app
    restart: always
    environment:
      - NODE_PATH=/usr/src/node_modules
      - NODE_ENV=development
    networks:
      - pal-network
    command: "npm run dev"
  backend:
    build:
      context: ./backend
      target: builder
    volumes:
      - ./backend/app:/app
      - ./media/:/uploads/
      - ./logs/backend:/var/log/backend
    env_file:
      - .env
    restart: always
    networks:
      - pal-network
    depends_on:
      - mongo
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --root-path /api --reload
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    networks:
      - pal-network
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - .env
    networks:
      - pal-network
    depends_on:
      - mongo
  nginx:
    restart: always
    build: ./nginx/
    volumes:
      - ./nginx/ssl/key.pem:/root/ssl/key.pem
      - ./nginx/ssl/cert.pem:/root/ssl/cert.pem
      - ./logs/nginx:/var/log/nginx/
      - ./media/:/www/media/
    ports:
      - "443:443"
    depends_on:
      - backend
      - frontend
      - mongo
      - mongo-express
      - es
      - kibana
    networks:
      - pal-network

  es:
    image: 'bitnami/elasticsearch:latest'
    container_name: es
    restart: always
    volumes:
      - data_es:/bitnami/elasticsearch/data
      - ./elasticsearch/my_elasticsearch.yml:/opt/bitnami/elasticsearch/config/my_elasticsearch.yml
    env_file:
      - .es.env
    networks:
      - pal-network
  kibana:
    image: 'bitnami/kibana:latest'
    container_name: kibana
    env_file:
      - .es.env
    depends_on:
      - es
    networks:
      - pal-network
    ports:
      - "5601:5601"